### ISSUE TITLE
Wot not credit ?

### ISSUE THREAD

**Issue by 3ative** [JOHLC/transparentblue#34]
**Describe the solution you'd like**
Crediting my "3ative Blue Theme" Theme that was used as (at least) a reference. 😉

![image](https://user-images.githubusercontent.com/51385971/195599104-9422d6f3-08a9-4a38-aae5-a5c7318e0f4d.png)

Thanks 👍

**Comment by JOHLC** [comment]
I actually used to have the following listed for credit:
https://github.com/naofireblade/clear-theme-dark -- because that is where I got started, and was my reference material  
See: [https://github.com/JOHLC/transparentblue/blob/0fb6656a6e0da75f88fe4952eb4129a0929d9160/README.md](https://github.com/JOHLC/transparentblue/blob/0fb6656a6e0da75f88fe4952eb4129a0929d9160/README.md) 

It has changed so much since, that I had removed it from the readme. 
If I copied anything, I believe it was only your MIT license file. 

That file is now updated, see: https://github.com/JOHLC/transparentblue/blob/main/LICENSE

**Comment by JOHLC** [comment]
Also added link to your theme

Closed [commit 4d5de2fe3c66f8f614edfdb3ff31980f079b711b](https://github.com/JOHLC/transparentblue/commit/4d5de2fe3c66f8f614edfdb3ff31980f079b711b)

**Comment by 3ative** [comment]
Spectacular, more than I hoped. 
I will add a link back to yours in my theme too now. 🫶
