### ISSUE TITLE
Color for "on" status is not displayed since 2022.12

### ISSUE THREAD

**Issue by Opontios** [JOHLC/transparentblue#35]
Since 2022.12 the color for  "on" status of entities in custom button card is not displayed, if not additionally defined in the card.

**Comment by JOHLC** [comment]
> Since 2022.12 the color for "on" status of entities in custom button card is not displayed, if not additionally defined in the card.

What variable are you using in the custom button card to color 'on' state?

**Comment by Opontios** [comment]
If I define color for states, it works, but then it has nothing to do with the theme. I meant that by default, if you didn't define a color for on state, the theme was changing the "on" color to yellow, but it stopped after the breaking changes have been done to the frontend color definitions. I don't know which latest update exactly do you mean, but no, nothing has changed, cause I'm always on the latest updates.

**Comment by JOHLC** [comment]
On the [latest version of the theme](https://github.com/JOHLC/transparentblue/releases#:~:text=Compare-,v2022.12.1,-%2D%20a%20few%20changes), I have removed the "paper-item-icon-active-color" variable

This is so that it will use the default icon colors for states after HA 2022.12  (See beleow) 

It sounds like the issue is with the Custom Button card, so I would suggest you review open/closed issues @ https://github.com/custom-cards/button-card/issues

Also see: https://developers.home-assistant.io/blog/2022/12/07/entity-color-changes/
````
From the Home Assistant Core 2022.12 release, we are using different colors per domain when an entity is active. These CSS variables are no longer used:

--paper-item-icon-active-color
--state-icon-active-color
This means that any theme that has previously overridden these CSS variables will use the built-in colors for active states. All theses new colors are available as CSS variables too.
````
